name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r mkdocs-pdf-export-plugin/requirements.txt  # Correct file path with forward slashes
      - run: mkdocs build  # This will generate the PDFs and build the site
      - name: Upload Artifact for GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: site/  # This is the default folder for MkDocs output
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
